### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by klenne** [i7solar/Akamai#1]
remote: Repository not found.
        fatal: repository 'https://github.com/SolarSystems-Software/HTTP2Client/' not found

**Comment by i7solar** [comment]
>         remote: Repository not found.
> 
>         fatal: repository 'https://github.com/SolarSystems-Software/HTTP2Client/' not found

![image](https://github.com/i7solar/Akamai/assets/63272358/d296a509-ad11-485f-b468-5c20ac76b32e)

I have included instructions for this issue in the readme.
