### ISSUE TITLE
remote: Repository not found.

### ISSUE THREAD

**Issue by LincolnKermit** [i7solar/Akamai#4]
Hi, after downloading repository and launch it with `go run main.go` I got this error:

`x@x Akamai % go run main.go 
go: github.com/SolarSystems-Software/HTTP2Client@v0.0.0-20210706145816-cc0ec4d07608: invalid version: git ls-remote -q origin in /Users/x/go/pkg/mod/cache/vcs/6fef8992c8b436679a9eda4c41e185ee55d5910d27225798a23c8bc1c652aa1b: exit status 128:
        remote: Repository not found.
        fatal: repository 'https://github.com/SolarSystems-Software/HTTP2Client/' not found
x@x Akamai % `

**Comment by OPwasNotAvailable** [comment]
Same

**Comment by LincolnKermit** [comment]
Repository seems to be inactive, I created a new one.

[Akamai Wiki](https://github.com/LincolnKermit/akamai-bot-manager-unofficial)
